remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: PYro Tools
description: A library of Python scripts that can be used to model wildfire behavior, effects, and emissions
